src/objects/S360_Form_Config__c.object
<CustomObject>
    <fields>
        <fullName>JSON__c</fullName>
        <description>Text Area to hold the JSON to format the Form</description>
        <label>JSON</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Form Config</label>
    <nameField>
        <label>Form Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FormBuilder.cls
public class FormBuilder {
    @AuraEnabled
    public static String getComponentConfig(String formName,String formId){
        List<S360_Form_Config__c> formConfigs;
        if(formId != '')
        {
        	formConfigs = [select JSON__c from S360_Form_Config__c where id = :formId limit 1];
        }else
        {
            formConfigs = [select JSON__c from S360_Form_Config__c where name = :formName limit 1];
        }
        if(formConfigs.size()==1){
            return formConfigs[0].JSON__c;
        }else{
            return '';
        }
    }
}